// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getShortURLByPath = `-- name: GetShortURLByPath :one
SELECT id, short_path, original_url, created_at FROM short_urls
WHERE short_path = $1 LIMIT 1
`

func (q *Queries) GetShortURLByPath(ctx context.Context, shortPath string) (ShortUrl, error) {
	row := q.db.QueryRow(ctx, getShortURLByPath, shortPath)
	var i ShortUrl
	err := row.Scan(
		&i.ID,
		&i.ShortPath,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}
