version: '3.8'

services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_DB: urlshortener_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

